# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog,QApplication,QDialog,QLabel
import ctypes



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.browse = QtWidgets.QPushButton(self.centralwidget)
        self.browse.setGeometry(QtCore.QRect(850, 0, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.browse.setFont(font)
        self.browse.setObjectName("browse")
        self.filename = QtWidgets.QLineEdit(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(675, 60, 481, 21))
        self.filename.setObjectName("filename")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(0, 80, 1081, 501))
        self.image.setText("")
        self.image.setObjectName("image")
        
        self.SetBackground = QtWidgets.QPushButton(self.centralwidget)
        self.SetBackground.setGeometry(QtCore.QRect(850, 960, 121, 41))
        self.SetBackground.setObjectName("SetBackground")
        self.SetBackground.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1447, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.browse.clicked.connect(self.browsefiles)
        
        self.SetBackground.clicked.connect(self.changeBG)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browse.setText(_translate("MainWindow", "Browse"))
        self.SetBackground.setText(_translate("MainWindow", "Apply"))

    def browsefiles(self):
        global path
        fname = QFileDialog.getOpenFileName(MainWindow,"Select an Image","C:\Test","Image files (*.jpg *.gif *.png)")
        path = fname[0]
        self.filename.setText(fname[0])
        self.displayimage(fname)
        

    def displayimage(self,fname):
        pixmap = QtGui.QPixmap(fname[0])
        self.image.setPixmap(pixmap)
        self.image.resize(pixmap.width(),pixmap.height())


    def changeBG(self):
         SPI_SETDESKWALLPAPER = 20
         ctypes.windll.user32.SystemParametersInfoW(SPI_SETDESKWALLPAPER, 0, path, 3)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())
